### ISSUE TITLE
Reduce training time for new and existing users

### ISSUE THREAD

**Issue by craig-landry** [medic/product-initiatives#61]
# Overview
Support improved learnability for new and existing users by aligning the CHT's user experience more closely with Android UX and [material design patterns](https://material.io/), which will make the CHT look and feel more like other Android apps that healthworkers are using. This will also improve the CHT’s scalability by ensuring our mobile-first framework has room to support more use cases and functionality. See [this forum post](https://forum.communityhealthtoolkit.org/t/updates-to-the-cht-ui-ux/1998) for additional context.

#### High Level Approach

The evolution of the UI will happen in stages, and the list below illustrates the order in which we expect the work to be done. Some of these stages will include a [Feature Flag](https://docs.communityhealthtoolkit.org/apps/guides/updates/feature-flags/) that will enable users to continue to see the old version of the UI for a period of time. The feature flags will enable projects to roll out these UI changes in batches instead of all at once. Once all stages have been complete, the feature flags will be removed and the old version of the UI will no longer be available in the app. 

## Next
- [ ] Remove all feature flags
- [ ] Navigation

## Done

- [x] [Floating Action Button](https://github.com/medic/cht-core/issues/7998) (2023 Q2)
- [x] [More options](https://github.com/medic/cht-core/issues/7872) (2022 Q4)
- [x] [Bulk Delete on Reports tab](https://github.com/medic/cht-core/issues/7778) (2022 Q3)
- [x] [Search on Reports and Contacts tab](https://github.com/medic/cht-core/issues/7746) (2022 Q3)
- [x] [Filters on the Reports tab](https://github.com/medic/cht-core/issues/7653) (2022 Q2)

--- 

### February 2023 - FAB

The fifth step of the UI evolution moves additive actions from the action bar to a Floating Action Bar.

- [GitHub issue #7998](https://github.com/medic/cht-core/issues/7998)

_Available in [4.2.0](https://github.com/medic/cht-core/milestone/109)_
_Feature Flag: `can_view_old_action_bar`_

### November 2022 - More options

The fourth step of the UI evolution moves supplemental  actions from the action bars to the "More Options" "`⋮`" menu.

- [GitHub issue #7872](https://github.com/medic/cht-core/issues/7872)

_Available in [4.2.0](https://github.com/medic/cht-core/milestone/109)_
_Feature Flag: `can_view_old_action_bar`_

### September 2022 - Bulk Delete on Reports tab

The third step of the UI evolution updates how Bulk Delete is handled on the Reports tab.

- [Forum post](https://forum.communityhealthtoolkit.org/t/experience-with-bulk-deleting-reports/2142)
- [GitHub issue #7778](https://github.com/medic/cht-core/issues/7778)

_Available in [4.1.0](https://github.com/medic/cht-core/milestone/105?closed=1)_
_Feature Flag: None_

### August 2022 - Search on Reports and Contacts tab

The second step of the UI evolution updates how Search is handled on the Reports and Contacts tabs.

- [Forum post](https://forum.communityhealthtoolkit.org/t/updates-to-the-search-feature/2107)
- [GitHub issue #7746](https://github.com/medic/cht-core/issues/7746)

_Available in [3.17.0](https://github.com/medic/cht-core/milestone/104?closed=1)_
_Feature Flag: `can_view_old_filter_and_search`_

### June 2022 - Filters on the Reports tab 

The first step of the evolution updates how Filters are displayed on the Reports tab.

- [Forum Post](https://forum.communityhealthtoolkit.org/t/feature-testing-filters/1917)
- [GitHub issue #7653](https://github.com/medic/cht-core/issues/7653)

_Available in [3.17.0](https://github.com/medic/cht-core/milestone/104?closed=1)_
_Feature Flag: `can_view_old_filter_and_search`_

**Comment by latin-panda** [comment]
[Filter work](https://github.com/medic/cht-core/issues/7653)

**Comment by latin-panda** [comment]
[Search bar redesign](https://github.com/medic/cht-core/issues/7746)

**Comment by andrablaj** [comment]
Closing as marked as `Done`
